// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aofvzqxjepgnokxoejaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvZnZ6cXhqZXBnbm9reG9lamF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MzY2OTEsImV4cCI6MjA1NTMxMjY5MX0.YKno39PuRrjb0iDlZ-RDdY_kySpWTjYTu0xVOLI5fDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);